# Generated by Django 5.1.7 on 2025-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certs/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
    ]
