services:
  - type: web
    name: wageway
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
    startCommand: daphne WageWay.asgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: WageWay.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'True'
      - key: REDIS_URL
        fromService:
          name: wageway-redis
          key: REDIS_URL

    autoDeploy: true
