# Generated by Django 5.1.7 on 2025-06-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customerprofile_bio_customerprofile_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('service_area', models.CharField(max_length=100)),
                ('available_days', models.CharField(max_length=100)),
                ('availability_time', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed'), ('per_job', 'Per Job')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('certification', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.providerprofile')),
            ],
        ),
    ]
