# Generated by Django 5.1.7 on 2025-06-16 09:05

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='availability_time',
        ),
        migrations.AddField(
            model_name='service',
            name='accepted_payments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card')], max_length=33),
        ),
        migrations.AddField(
            model_name='service',
            name='cancellation_policy',
            field=models.CharField(choices=[('anytime', 'Anytime'), ('before_24h', 'Before 24 Hours'), ('before_12h', 'Before 12 Hours')], default='anytime', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='contact_phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='job_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='job_type',
            field=models.CharField(choices=[('one_time', 'One-Time'), ('recurring', 'Recurring')], default='one_time', max_length=15),
        ),
        migrations.AddField(
            model_name='service',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='verified_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='available_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=27),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Cleaning', 'Cleaning'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Carpentry', 'Carpentry'), ('Tutoring', 'Tutoring'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_area',
            field=models.CharField(max_length=150),
        ),
    ]
