# Generated by Django 5.1.7 on 2025-06-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_confirmed_and_more'),
        ('jobboard', '0003_jobapplication_poster_confirmed_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'job', 'review_type')},
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'booking', 'review_type'), ('reviewer', 'job', 'review_type')},
        ),
    ]
