# Generated by Django 5.1.7 on 2025-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='preferred_payment',
            field=models.CharField(choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Service'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
