# Generated by Django 5.1.7 on 2025-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_jobpost_preferred_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='poster_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='worker_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='preferred_payment',
            field=models.CharField(choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Service'), ('other', 'Other')], default='upi', max_length=20),
        ),
    ]
