# Generated by Django 5.1.7 on 2025-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='issue_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='material_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_payment',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_response',
            field=models.CharField(choices=[('waiting', 'Waiting for Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
